### ISSUE TITLE
英文原版

### ISSUE THREAD

**Issue by Calvin-he** [ohhoney1/Vue.js-Source-Code-line-by-line#1]
你好，我对vuejs的设计也挺感兴趣的，很高兴能看到你的文章。
请问，方便把英文原版也放上来吗？

**Comment by ohhoney1** [comment]
@Calvin-he https://medium.com/@oneminutejs/a-deep-dive-in-the-vue-js-source-code-0-table-of-contents-170dcc3c8ec 这是原文地址，需要翻墙查看。这半年没接触vue了，加上工作太忙，翻译的事耽搁了。

**Comment by Calvin-he** [comment]
@ohhoney1 刚开始研究Vue的源码，在寻找各种资料。多谢！

**Comment by Calvin-he** [comment]
@ohhoney1 刚开始研究Vue的源码，在寻找各种资料。多谢！

**Comment by ohhoney1** [comment]
> @ohhoney1 刚开始研究Vue的源码，在寻找各种资料。多谢！

不客气。推荐几个资料：
[Vue.js 技术揭秘](https://ustbhuangyi.github.io/vue-analysis/)
[剖析 Vue.js 内部运行机制](https://juejin.im/book/5a36661851882538e2259c0f)
[《深入浅出Vue.js》](https://item.jd.com/12573168.html)
